name: Test + Zip publish
on:
  release:
    types: [created]
jobs:
  build:
    name: Create_package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-hotspot'
          java-version: '11'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: azureFunctionsPackageZip
      - name: Rename zip
        run: mkdir build/upload & mv build/azure-functions/http-trigger-gradle-template.zip build/upload/${{env.RELEASE_VERSION}}.zip
      - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          source_dir: 'build/upload'
          connection_string: ${{ secrets.CONNECTIONSTRING }}
          container_name: 'bucket'
          extra_args: '--pattern *.zip'
          sync: false
